### ISSUE TITLE
The Deposit transaction signature message in ios14 displays garbled characters

### ISSUE THREAD

**Issue by Dawn-githup** [godwokenrises/light-godwoken#203] opened 2022-09-30 06:54 UTC
## **Describe the bug**
The Deposit transaction signature message in ios14 displays garbled characters

1. Initiate deposit transaction in Metamask browser
2. Jump to signature page

![image](https://user-images.githubusercontent.com/77844990/193209225-0ff8202e-1c81-42a4-a213-2bd8195ff5ba.png)

**Comment by Dawn-githup** [comment] 2022-10-09 11:34
![image](https://user-images.githubusercontent.com/77844990/194754519-a1ccf978-8cc5-4b96-bbf4-ecfa16a2ea9e.png)
> Getting the test token will also be garbled

**Comment by ShookLyngs** [comment] 2022-10-26 14:25
It seems this issue is caused by a specific behaviour of MetaMask: when the message that needs to be signed is a hex string, MetaMask tries to convert it to utf-8 string, and apparently it doesn't work for in cases.

MetaMask team suggest us to use `signTypedData_v4` instead of `personal_sign`, I think for now we should mark the issue as "wontfix", @Flouse  what do you think?

Related issue:
https://github.com/MetaMask/metamask-extension/issues/3931

**Comment by ShookLyngs** [comment] 2023-02-10 05:46
This issue is not going to be fixed any time soon, so closing this issue.
But we will get to this whenever the chance comes.

**Closed by ShookLyngs** 2023-02-10 05:46 UTC
Labels: wontfix, P-Low, UI
